module.exports = {
    appPackage: "com.sjgwer.dbbyh",
    appName: "热血传说",
    assets: {
        newVersionTip: "./assets/new_version_tip.png",
        newVersionConfirm: "./assets/new_version_confirm.png",
        loginButton: "./assets/login_btn.png",
        agreeNo: "./assets/agree_no.png",
        agreeYes: "./assets/agree_yes.png",
    },
    permissionTexts: [
        "允许",
        "始终允许",
        "仅在使用中允许",
        "继续允许",
    ],
    versionTipThreshold: 0.8,
    login: {
        enabled: false,
        mode: "login_full",
        account: "we7070015",
        password: "756458",
        ids: {
            userInput: "huanyu_defaultlogin_et_user",
            pwdInput: "huanyu_defaultlogin_et_pwd",
            loginButton: "huanyu_defaultlogin_bt_login",
        },
        placeholders: {
            user: "请输入用户名",
            pwd: "请输入密码",
        },
        timeouts: {
            pageReady: 5000,
            node: 1200,
            afterInput: 1000,
            afterClick: 800,
        },
    },
    server: {
        enabled: true,
        mode: "server_full",
        targetLabel: "怀旧1区",
        assets: {
            greenEntryPageReady: "./assets/server_green_entry_page_ready.png",
            greenEntry: "./assets/server_green_entry.png",
            serverSelectPageReady: "./assets/server_server_select_page_ready.png",
            currentHuai1: "./assets/server_current_huai_1.png",
            serverSelectEntry: "./assets/server_server_select_entry.png",
            group1To10: "./assets/server_group_1_10.png",
            zoneHuai1: "./assets/server_zone_huai_1.png",
            zoneHuai1Selected: "./assets/server_zone_huai_1_selected.png",
            enterGame: "./assets/server_enter_game.png",
            serverResult: "./assets/server_result_ready.png",
        },
        threshold: 0.8,
        timeouts: {
            pageReady: 12000,
            afterClick: 1000,
            result: 5000,
        },
    },
    debug: {
        screenshotEnabled: true,
    },
};
